library(tibble)

## Create simplified arXiv taxonomy
arxiv_taxonomy <- tribble(
  ~subcategory, ~subcategory_name, ~category_name, ~category,
  
  # Computer Science
  "cs.AI", "Artificial Intelligence", "Computer Science", "cs",
  "cs.AR", "Hardware Architecture", "Computer Science", "cs",
  "cs.CC", "Computational Complexity", "Computer Science", "cs",
  "cs.CE", "Computational Engineering, Finance, and Science", "Computer Science", "cs",
  "cs.CG", "Computational Geometry", "Computer Science", "cs",
  "cs.CL", "Computation and Language", "Computer Science", "cs",
  "cs.CR", "Cryptography and Security", "Computer Science", "cs",
  "cs.CV", "Computer Vision and Pattern Recognition", "Computer Science", "cs",
  "cs.CY", "Computers and Society", "Computer Science", "cs",
  "cs.DB", "Databases", "Computer Science", "cs",
  "cs.DC", "Distributed, Parallel, and Cluster Computing", "Computer Science", "cs",
  "cs.DL", "Digital Libraries", "Computer Science", "cs",
  "cs.DM", "Discrete Mathematics", "Computer Science", "cs",
  "cs.DS", "Data Structures and Algorithms", "Computer Science", "cs",
  "cs.ET", "Emerging Technologies", "Computer Science", "cs",
  "cs.FL", "Formal Languages and Automata Theory", "Computer Science", "cs",
  "cs.GL", "General Literature", "Computer Science", "cs",
  "cs.GR", "Graphics", "Computer Science", "cs",
  "cs.GT", "Computer Science and Game Theory", "Computer Science", "cs",
  "cs.HC", "Human-Computer Interaction", "Computer Science", "cs",
  "cs.IR", "Information Retrieval", "Computer Science", "cs",
  "cs.IT", "Information Theory", "Computer Science", "cs",
  "cs.LG", "Machine Learning", "Computer Science", "cs",
  "cs.LO", "Logic in Computer Science", "Computer Science", "cs",
  "cs.MA", "Multiagent Systems", "Computer Science", "cs",
  "cs.MM", "Multimedia", "Computer Science", "cs",
  "cs.MS", "Mathematical Software", "Computer Science", "cs",
  "cs.NA", "Numerical Analysis", "Computer Science", "cs",
  "cs.NE", "Neural and Evolutionary Computing", "Computer Science", "cs",
  "cs.NI", "Networking and Internet Architecture", "Computer Science", "cs",
  "cs.OH", "Other Computer Science", "Computer Science", "cs",
  "cs.OS", "Operating Systems", "Computer Science", "cs",
  "cs.PF", "Performance", "Computer Science", "cs",
  "cs.PL", "Programming Languages", "Computer Science", "cs",
  "cs.RO", "Robotics", "Computer Science", "cs",
  "cs.SC", "Symbolic Computation", "Computer Science", "cs",
  "cs.SD", "Sound", "Computer Science", "cs",
  "cs.SE", "Software Engineering", "Computer Science", "cs",
  "cs.SI", "Social and Information Networks", "Computer Science", "cs",
  "cs.SY", "Systems and Control", "Computer Science", "cs",
  
  # Economics
  "econ.EM", "Econometrics", "Economics", "econ",
  "econ.GN", "General Economics", "Economics", "econ",
  "econ.TH", "Theoretical Economics", "Economics", "econ",
  
  # Electrical Engineering and Systems Science
  "eess.AS", "Audio and Speech Processing", "Electrical Engineering and Systems Science", "eess",
  "eess.IV", "Image and Video Processing", "Electrical Engineering and Systems Science", "eess",
  "eess.SP", "Signal Processing", "Electrical Engineering and Systems Science", "eess",
  "eess.SY", "Systems and Control", "Electrical Engineering and Systems Science", "eess",
  
  # Mathematics
  "math.AC", "Commutative Algebra", "Mathematics", "math",
  "math.AG", "Algebraic Geometry", "Mathematics", "math",
  "math.AP", "Analysis of PDEs", "Mathematics", "math",
  "math.AT", "Algebraic Topology", "Mathematics", "math",
  "math.CA", "Classical Analysis and ODEs", "Mathematics", "math",
  "math.CO", "Combinatorics", "Mathematics", "math",
  "math.CT", "Category Theory", "Mathematics", "math",
  "math.CV", "Complex Variables", "Mathematics", "math",
  "math.DG", "Differential Geometry", "Mathematics", "math",
  "math.DS", "Dynamical Systems", "Mathematics", "math",
  "math.FA", "Functional Analysis", "Mathematics", "math",
  "math.GM", "General Mathematics", "Mathematics", "math",
  "math.GN", "General Topology", "Mathematics", "math",
  "math.GR", "Group Theory", "Mathematics", "math",
  "math.GT", "Geometric Topology", "Mathematics", "math",
  "math.HO", "History and Overview", "Mathematics", "math",
  "math.IT", "Information Theory", "Mathematics", "math",
  "math.KT", "K-Theory and Homology", "Mathematics", "math",
  "math.LO", "Logic", "Mathematics", "math",
  "math.MG", "Metric Geometry", "Mathematics", "math",
  "math.MP", "Mathematical Physics", "Mathematics", "math",
  "math.NA", "Numerical Analysis", "Mathematics", "math",
  "math.NT", "Number Theory", "Mathematics", "math",
  "math.OA", "Operator Algebras", "Mathematics", "math",
  "math.OC", "Optimization and Control", "Mathematics", "math",
  "math.PR", "Probability", "Mathematics", "math",
  "math.QA", "Quantum Algebra", "Mathematics", "math",
  "math.RA", "Rings and Algebras", "Mathematics", "math",
  "math.RT", "Representation Theory", "Mathematics", "math",
  "math.SG", "Symplectic Geometry", "Mathematics", "math",
  "math.SP", "Spectral Theory", "Mathematics", "math",
  "math.ST", "Statistics Theory", "Mathematics", "math",
  
  # Physics - Astrophysics
  # "astro-ph.CO", "Cosmology and Nongalactic Astrophysics", "Astrophysics", "astro-ph",
  # "astro-ph.EP", "Earth and Planetary Astrophysics", "Astrophysics", "astro-ph",
  # "astro-ph.GA", "Astrophysics of Galaxies", "Astrophysics", "astro-ph",
  # "astro-ph.HE", "High Energy Astrophysical Phenomena", "Astrophysics", "astro-ph",
  # "astro-ph.IM", "Instrumentation and Methods for Astrophysics", "Astrophysics", "astro-ph",
  # "astro-ph.SR", "Solar and Stellar Astrophysics", "Astrophysics", "astro-ph",
  "astro-ph.CO", "Cosmology and Nongalactic Astrophysics", "Physics", "physics",
  "astro-ph.EP", "Earth and Planetary Astrophysics", "Physics", "physics",
  "astro-ph.GA", "Astrophysics of Galaxies", "Physics", "physics",
  "astro-ph.HE", "High Energy Astrophysical Phenomena", "Physics", "physics",
  "astro-ph.IM", "Instrumentation and Methods for Astrophysics", "Physics", "physics",
  "astro-ph.SR", "Solar and Stellar Astrophysics", "Physics", "physics",
  "astro-ph.GEN", "Astrophysics - General", "Physics", "physics",
  
  # Physics - Condensed Matter
  # "cond-mat.dis-nn", "Disordered Systems and Neural Networks", "Condensed Matter", "cond-mat",
  # "cond-mat.mes-hall", "Mesoscale and Nanoscale Physics", "Condensed Matter", "cond-mat",
  # "cond-mat.mtrl-sci", "Materials Science", "Condensed Matter", "cond-mat",
  # "cond-mat.other", "Other Condensed Matter", "Condensed Matter", "cond-mat",
  # "cond-mat.quant-gas", "Quantum Gases", "Condensed Matter", "cond-mat",
  # "cond-mat.soft", "Soft Condensed Matter", "Condensed Matter", "cond-mat",
  # "cond-mat.stat-mech", "Statistical Mechanics", "Condensed Matter", "cond-mat",
  # "cond-mat.str-el", "Strongly Correlated Electrons", "Condensed Matter", "cond-mat",
  # "cond-mat.supr-con", "Superconductivity", "Condensed Matter", "cond-mat",
  "cond-mat.dis-nn", "Disordered Systems and Neural Networks", "Physics", "physics",
  "cond-mat.mes-hall", "Mesoscale and Nanoscale Physics", "Physics", "physics",
  "cond-mat.mtrl-sci", "Materials Science", "Physics", "physics",
  "cond-mat.other", "Other Condensed Matter", "Physics", "physics",
  "cond-mat.quant-gas", "Quantum Gases", "Physics", "physics",
  "cond-mat.soft", "Soft Condensed Matter", "Physics", "physics",
  "cond-mat.stat-mech", "Statistical Mechanics", "Physics", "physics",
  "cond-mat.str-el", "Strongly Correlated Electrons", "Physics", "physics",
  "cond-mat.supr-con", "Superconductivity", "Physics", "physics",
  "cond-mat.GEN", "Condensed Matter - General", "Physics", "physics",
  
  # Physics - General Relativity
  # "gr-qc", "General Relativity and Quantum Cosmology", "General Relativity and Quantum Cosmology", "gr-qc",
  "gr-qc", "General Relativity and Quantum Cosmology", "Physics", "physics",
  
  # Physics - High Energy Physics
  # "hep-ex", "High Energy Physics - Experiment", "High Energy Physics - Experiment", "hep-ex",
  # "hep-lat", "High Energy Physics - Lattice", "High Energy Physics - Lattice", "hep-lat",
  # "hep-ph", "High Energy Physics - Phenomenology", "High Energy Physics - Phenomenology", "hep-ph",
  # "hep-th", "High Energy Physics - Theory", "High Energy Physics - Theory", "hep-th",
  "hep-ex", "High Energy Physics - Experiment", "Physics", "physics",
  "hep-lat", "High Energy Physics - Lattice", "Physics", "physics",
  "hep-ph", "High Energy Physics - Phenomenology", "Physics", "physics",
  "hep-th", "High Energy Physics - Theory", "Physics", "physics",
  
  # Physics - Mathematical Physics
  # "math-ph", "Mathematical Physics", "Mathematical Physics", "math-ph",
  "math-ph", "Mathematical Physics", "Physics", "physics",
  
  # Physics - Nonlinear Sciences
  # "nlin.AO", "Adaptation and Self-Organizing Systems", "Nonlinear Sciences", "nlin",
  # "nlin.CD", "Chaotic Dynamics", "Nonlinear Sciences", "nlin",
  # "nlin.CG", "Cellular Automata and Lattice Gases", "Nonlinear Sciences", "nlin",
  # "nlin.PS", "Pattern Formation and Solitons", "Nonlinear Sciences", "nlin",
  # "nlin.SI", "Exactly Solvable and Integrable Systems", "Nonlinear Sciences", "nlin",
  "nlin.AO", "Adaptation and Self-Organizing Systems", "Physics", "physics",
  "nlin.CD", "Chaotic Dynamics", "Physics", "physics",
  "nlin.CG", "Cellular Automata and Lattice Gases", "Physics", "physics",
  "nlin.PS", "Pattern Formation and Solitons", "Physics", "physics",
  "nlin.SI", "Exactly Solvable and Integrable Systems", "Physics", "physics",
  
  # Physics - Nuclear
  # "nucl-ex", "Nuclear Experiment", "Nuclear Experiment", "nucl-ex",
  # "nucl-th", "Nuclear Theory", "Nuclear Theory", "nucl-th",
  "nucl-ex", "Nuclear Experiment", "Physics", "physics",
  "nucl-th", "Nuclear Theory", "Physics", "physics",
  
  # Physics - Physics
  "physics.acc-ph", "Accelerator Physics", "Physics", "physics",
  "physics.ao-ph", "Atmospheric and Oceanic Physics", "Physics", "physics",
  "physics.app-ph", "Applied Physics", "Physics", "physics",
  "physics.atm-clus", "Atomic and Molecular Clusters", "Physics", "physics",
  "physics.atom-ph", "Atomic Physics", "Physics", "physics",
  "physics.bio-ph", "Biological Physics", "Physics", "physics",
  "physics.chem-ph", "Chemical Physics", "Physics", "physics",
  "physics.class-ph", "Classical Physics", "Physics", "physics",
  "physics.comp-ph", "Computational Physics", "Physics", "physics",
  "physics.data-an", "Data Analysis, Statistics and Probability", "Physics", "physics",
  "physics.ed-ph", "Physics Education", "Physics", "physics",
  "physics.flu-dyn", "Fluid Dynamics", "Physics", "physics",
  "physics.gen-ph", "General Physics", "Physics", "physics",
  "physics.geo-ph", "Geophysics", "Physics", "physics",
  "physics.hist-ph", "History and Philosophy of Physics", "Physics", "physics",
  "physics.ins-det", "Instrumentation and Detectors", "Physics", "physics",
  "physics.med-ph", "Medical Physics", "Physics", "physics",
  "physics.optics", "Optics", "Physics", "physics",
  "physics.plasm-ph", "Plasma Physics", "Physics", "physics",
  "physics.pop-ph", "Popular Physics", "Physics", "physics",
  "physics.soc-ph", "Physics and Society", "Physics", "physics",
  "physics.space-ph", "Space Physics", "Physics", "physics",
  
  # Quantum Physics
  "quant-ph", "Quantum Physics", "Physics", "physics",
  # "quant-ph", "Quantum Physics", "Quantum Physics", "quant-ph",
  
  # Quantitative Biology
  "q-bio.BM", "Biomolecules", "Quantitative Biology", "q-bio",
  "q-bio.CB", "Cell Behavior", "Quantitative Biology", "q-bio",
  "q-bio.GN", "Genomics", "Quantitative Biology", "q-bio",
  "q-bio.MN", "Molecular Networks", "Quantitative Biology", "q-bio",
  "q-bio.NC", "Neurons and Cognition", "Quantitative Biology", "q-bio",
  "q-bio.OT", "Other Quantitative Biology", "Quantitative Biology", "q-bio",
  "q-bio.PE", "Populations and Evolution", "Quantitative Biology", "q-bio",
  "q-bio.QM", "Quantitative Methods", "Quantitative Biology", "q-bio",
  "q-bio.SC", "Subcellular Processes", "Quantitative Biology", "q-bio",
  "q-bio.TO", "Tissues and Organs", "Quantitative Biology", "q-bio",
  "q-bio.GEN", "Quantitative Biology - General", "Quantitative Biology", "q-bio",
  
  # Quantitative Finance
  "q-fin.CP", "Computational Finance", "Quantitative Finance", "q-fin",
  "q-fin.EC", "Economics", "Quantitative Finance", "q-fin",
  "q-fin.GN", "General Finance", "Quantitative Finance", "q-fin",
  "q-fin.MF", "Mathematical Finance", "Quantitative Finance", "q-fin",
  "q-fin.PM", "Portfolio Management", "Quantitative Finance", "q-fin",
  "q-fin.PR", "Pricing of Securities", "Quantitative Finance", "q-fin",
  "q-fin.RM", "Risk Management", "Quantitative Finance", "q-fin",
  "q-fin.ST", "Statistical Finance", "Quantitative Finance", "q-fin",
  "q-fin.TR", "Trading and Market Microstructure", "Quantitative Finance", "q-fin",
  
  # Statistics
  "stat.AP", "Applications", "Statistics", "stat",
  "stat.CO", "Computation", "Statistics", "stat",
  "stat.ME", "Methodology", "Statistics", "stat",
  "stat.ML", "Machine Learning", "Statistics", "stat",
  "stat.OT", "Other Statistics", "Statistics", "stat",
  "stat.TH", "Statistics Theory", "Statistics", "stat"
)